app:
  version: 1.0.0
  name: paas-kg

email:
  from_address: finstart.mailer@molbulak.com
  username: finstart.mailer
  password: Shaxz0da201306
  host: mail.molbulak.com
  address: mail.molbulak.com
  port: 25
  encoding: utf-8


alerts:
  emails:
    - a.itskovich@molbulak.com

fr:
  url: http://10.1.2.103:8091
  developer_id: 106567582

sh:
  executor: C:\Program Files\Git\bin\bash.exe

server:
  port: 8082

loggers:
  sql:
    backup_count: 3
  http:
    backup_count: 3

prod:
  db:
    host: localhost
    port: 5432
    user: postgres
    password: 92559255

dev:
  db:
    host: localhost
    port: 3
    user: postgres
    password: 92559255

  cherkzion:
    url: http://localhost:8081

